### ISSUE TITLE
I  can't  test  my custom data.

### ISSUE THREAD

**Issue by siam7tong** [swz30/MPRNet#10]
first  RuntimeError: Given groups=1, weight of size 96 3 3 3, expected input[1, 4, 225, 149] to have 3 channels, but got 4 channels instead
I  change  inp = Image.open(path_inp)  to   inp = Image.open(path_inp).convert('RGB') 
but than RuntimeError: The size of tensor a (296) must match the size of tensor b (298) at non-singleton dimension 3

thanks

**Comment by swz30** [comment]
Hi @siam7tong 

Could you please provide more details:
- Is your image in RGB color space, and what is the resolution?
- Which task are you trying?

**Comment by adityac8** [comment]
Hi @siam7tong 
We have added a quick demo to run our pre-trained models on a custom set of images.
You can have a look at [demo.py](https://github.com/swz30/MPRNet/blob/main/demo.py).

Thanks

**Comment by siam7tong** [comment]
thanks ,i got it.  
if i just have legacy photos ,how to train ?

**Comment by adityac8** [comment]
Hi,
We did not try it on legacy photos.

Thanks
