### ISSUE TITLE
Patch images size for stage2

### ISSUE THREAD

**Issue by lush-toner** [swz30/MPRNet#102]
Thank you for your research.

When I look at the code below,

In class method "def forward", 

stage 2 two patches are cropped horizontally (height x 0.5),

but I can see that in Figure 2 in the paper, stage 2 two patches are crops vertically (width x 1/2).

Is there any reason, why it is different?

![image](https://user-images.githubusercontent.com/77714576/147653460-30e831d4-6230-416b-9725-edc5b3415a1c.png)

![Screenshot from 2021-12-29 19-32-51](https://user-images.githubusercontent.com/77714576/147653236-44680dcb-1dc0-4543-8f6e-acb9760d92fb.png)

**Comment by adityac8** [comment]
Hi

Changing the crop from vertical to horizontal should not have any effect on the model performance.

Thanks
