### ISSUE TITLE
Training custom dataset - output is the same as input image

### ISSUE THREAD

**Issue by orydatadudes** [swz30/MPRNet#104]
hey
thank you for your work
i trained the model using costume dataset - blur people here is an example 

![33196_5](https://user-images.githubusercontent.com/64726228/149338706-0f8458e4-dace-4068-8284-86e6258b3300.png)

![33196_0](https://user-images.githubusercontent.com/64726228/149338749-2e787836-9fe6-4ab9-ae7a-9ec885acc7f6.png)

i tried to get over fit on a small datasets (6 paries of images , set train and validation to be the same )
the problem is that even after 1500 epoch the model learn to return the input image 
what can i do
thank you

**Comment by stefankubal** [comment]
Hi, sorry to be a pain as this is not an answer to your question, but instead a request.
I am very much struggling to get the deblurring to work in anyway on my system. 
Would you be available to perhaps help me identify what I am doing wrong. It would be a massive massive help to me :(

**Comment by adityac8** [comment]
Hi

The AI models generally need thousands of examples to learn. You could check our model on a standard publicly available paired dataset for your problem.

Thanks
