### ISSUE TITLE
Denoising Fog effect in Adobe Photoshop

### ISSUE THREAD

**Issue by AliNaqvi110** [swz30/MPRNet#109]
I have generated fog effects in Adobe Photoshop on an image I want to get back clear. Your models for denoising and deblurring dont work. Any Suggestions.

**Comment by adityac8** [comment]
Hi

For fog removal, you need to train our model on `fog - no fog` image pairs.
You can have a look at other restoration tasks datasets to get an estimate of the number of images needed.
Once the model is trained, you can test it on your images.

Thanks

**Comment by AliNaqvi110** [comment]
Thanks buddy I will try
