### ISSUE TITLE
out of memory 

### ISSUE THREAD

**Issue by erjihaoshi** [swz30/MPRNet#11]
1 when I train debluring model，patch_size=512,batch_size=1, rtx2080ti  cuda out of memory，I wander know how many
gpu memory should i use in this situation  ,because  I think path_size =256  a little bit  small for image

2  Have you ever try add gan loss to your model for ablation experiment?

**Comment by adityac8** [comment]
Hi @erjihaoshi 

No, we didn't try GAN loss. 

For a light-weight model, you can have a look [here](https://github.com/swz30/MPRNet/issues/6#issuecomment-787786769).

Thnaks
