### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by BALDman66** [swz30/MPRNet#111]
[](https://user-images.githubusercontent.com/59443639/163775574-16756a95-7d43-4625-b5ef-4823df02b28e.png)
I entered a 2048 * 2048 picture for test results showing insufficient memory but input small resolution pictures can be, I can ask me to test a big resolution image?
image

**Comment by swz30** [comment]
You can split the image into overlaped patches, perform inference on each patch, and then merge them. Here is an example of tiling https://github.com/swz30/Restormer/blob/55b1f83a60c3d874953b6affba5c0050ad1caa62/demo.py#L133
