### ISSUE TITLE
multi-process problems

### ISSUE THREAD

**Issue by ZhengWugeng** [swz30/MPRNet#114]
when I train the model, it shows " An attempt has been made to start a new process before the current process has finished its bootstrapping phase." What is the reason that lead to this?
![screenshot](https://user-images.githubusercontent.com/22239871/175214318-99057a93-58a4-452e-be88-85fc0cce8174.png)

**Comment by adityac8** [comment]
Please have a look at this [link](https://discuss.pytorch.org/t/runtimeerror-an-attempt-has-been-made-to-start-a-new-process-before-the-current-process-has-finished-its-bootstrapping-phase/145462) and see if it solves your error.
