### ISSUE TITLE
“RuntimeError: CUDA Out of memory” error

### ISSUE THREAD

**Issue by hoseindamavandi** [swz30/MPRNet#127]
when I want train deraing on a new dataset, I give this error:

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 240.00 MiB (GPU 0; 39.59 GiB total capacity; 37.51 GiB already allocated; 80.12 MiB free; 37.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

can you help me?

**Comment by 6jybuchiyu** [comment]
yes，you can set the parameter 'num_workers=0'
