### ISSUE TITLE
RuntimeError: CUDA out of memory when train

### ISSUE THREAD

**Issue by Zz1041328406** [swz30/MPRNet#15]
hello! when I use four GPU TiTanXP to train,it shows that CUDA out of memory.
Could you tell me how many GPUs you use,please.
Thanks very much.

**Comment by adityac8** [comment]
Hi @Zz1041328406 

Could you give details on what task are you trying to run and what dataset are you using.

Thanks

**Comment by Zz1041328406** [comment]
I tried to train the task : Deblurring, use the Dataset:Gopro(about 14G) , when batch_size chooses 16.

![J3LED4@U(D~R%6K(}}LCHOQ](https://user-images.githubusercontent.com/77730893/110301501-1f322700-8033-11eb-8837-7c10c8f247d4.png)

**Comment by adityac8** [comment]
Hi

We use 4 Tesla V100 GPUs to train our model.
You can use either of the options to train your model:
1. Use a smaller patch size by setting the variable `TRAIN_PS`
2. Use a smaller batch size  by setting the variable `BATCH_SIZE`
3. Use a lighter model as explained [here](https://github.com/swz30/MPRNet/issues/6#issuecomment-787786769)

Thanks
