### ISSUE TITLE
I wonder if your model can be used to restore old photos

### ISSUE THREAD

**Issue by syfbme** [swz30/MPRNet#18]
Old photo has some characteristic like noise, blur.

**Comment by syfbme** [comment]
> We did not try our model on such images.

Thanks for your reply. I notice that you trained deblur and denoise separately. In old photo, these 2 characteristic both exist. I don't know if your model is able to do deblur and denoise at the same time. Do you think it worth a try?

**Comment by adityac8** [comment]
If you have multi-degradation paired dataset, you can try and check how our model performs.
