### ISSUE TITLE
[Derain] Why Test100 only contain 98 image pairs? 

### ISSUE THREAD

**Issue by mayorx** [swz30/MPRNet#23]
[Test100](https://drive.google.com/drive/folders/12uv5sdg1mYsKJYv1v-9KcXL-ciFWFdAI?usp=sharing)

In [paper](https://arxiv.org/pdf/2102.02808.pdf), table 2, we can see Test100 contains 100 image pairs.

And ...  there are 2801 images in [Test2800-input](https://drive.google.com/drive/folders/104BC9aUpeRbvzBSVYDqjmg32gVMVT0Tj?usp=sharing), one image named ```926_10(1).jpg```  lol.

**Comment by swz30** [comment]
Hi @mayorx 

For Test100, we follow the same convention as the previous best method (MSPFN) and use 98 images for testing. 

Thank you for pointing the duplication in the Test2800-input; we have removed it from [Google Drive](https://drive.google.com/drive/folders/104BC9aUpeRbvzBSVYDqjmg32gVMVT0Tj?usp=sharing).

**Comment by mayorx** [comment]
Thanks for your reply
