### ISSUE TITLE
Question about evaluation of Hide dataset.

### ISSUE THREAD

**Issue by rimchang** [swz30/MPRNet#27]
Hi, thank you for your very cool work for image resotration.

I tried to evaluate Hide dataset. 

I downloaded the dataset using link you provide.

But input folder have 1,079 images and target folder have only 942 images.

Could you describe how to evaluate model for Hide dataset?

Did you evaluate on only 942 images?

Thank you

**Comment by swz30** [comment]
Hi @rimchang 

We evaluated MPRNet on 2025 test images. 

I just downloaded the test set on my end from the [link](https://drive.google.com/drive/folders/1nRsTXj4iTUkTvBhTcGg8cySK8nd3vlhK) and I confirm that both the input and target directories contain 2025 images each.

Please try downloading the dataset again.
