### ISSUE TITLE
Run this project on Windows

### ISSUE THREAD

**Issue by navyajain16** [swz30/MPRNet#31]
I am facing difficulty while running the code on windows.
It shows the following error on running train.py:
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.
            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:
                if __name__ == '__main__':
                    freeze_support()
                    ...
            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
Can anyone please help out with this ?

**Comment by swz30** [comment]
Hi @navyajain16,

Our model is built in PyTorch 1.1.0 and tested on Ubuntu 16.04 environment (Python3.7, CUDA9.0, cuDNN7.5). I am afraid, we have no plan of testing it on Windows.

**Comment by Cjh2312** [comment]
> I am facing difficulty while running the code on windows. It shows the following error on running train.py: RuntimeError: Attempt to start a new process before the current process has finished its bootstrapping phase. This probably means that you are on Windows and you have forgotten to use the proper idiom in the main module: if **name** == '**main**': freeze_support() ... The "freeze_support()" line can be omitted if the program is not going to be frozen to produce a Windows executable. Can anyone please help out with this ?

Have you solved it? Can you run through it on windows？

**Comment by MobinaBakhshpour** [comment]
> I am facing difficulty while running the code on windows. It shows the following error on running train.py: RuntimeError: Attempt to start a new process before the current process has finished its bootstrapping phase. This probably means that you are on Windows and you have forgotten to use the proper idiom in the main module: if **name** == '**main**': freeze_support() ... The "freeze_support()" line can be omitted if the program is not going to be frozen to produce a Windows executable. Can anyone please help out with this ?

Did you run it on Windows? I have this problem too.
