### ISSUE TITLE
Changing Batch Size?

### ISSUE THREAD

**Issue by DiegoCaumont** [swz30/MPRNet#32]
RuntimeError: CUDA out of memory. Tried to allocate 1.18 GiB (GPU 0; 24.00 GiB total capacity; 18.28 GiB already allocated; 549.31 MiB free; 21.26 GiB reserved in total by PyTorch)

This occurred when trying running demo.py using a 3296x2400 png. 

How can you reduce the batch size?

or 

How would you clear the cached memory using 'torch.cuda.empty_cache()'

P.S Nothing memory intensive was running in the background and I have already tried shutting down or restarting my PC. This works for smaller images, however, I am looking at if possible for higher dimensions.

**Comment by swz30** [comment]
Hi @DiegoCaumont 

You can check the issue [#13](https://github.com/swz30/MPRNet/issues/13#issuecomment-798870290). If you still get OOM error, I would suggest the following: Downsample the input image, perform inference, and upsample back to the original resolution.
