### ISSUE TITLE
Train on dual_pixels_dataset_canon?

### ISSUE THREAD

**Issue by pingjun18-li** [swz30/MPRNet#34]
Hello, thank you for your contribution.
I want to know have you tried to use dual pixel images to train your network?
for example dual_pixels_dataset_canon, which only contain 500 pairs dual pixel labels. 
if yes, can you share the codes or ideas about how use it on that projects?

**Comment by swz30** [comment]
Hi @pingjun18-li 

We did try it by participating in [NTIRE 2021 Defocus Deblurring using Dual-pixel Images Challenge](https://competitions.codalab.org/competitions/28049). We concatenate the left and right images and provide them as input to the network. Just replace the 3 channels with 6 in the following convolutional layers. 

https://github.com/swz30/MPRNet/blob/51b58bb2ec803162e9053c1269b170009ee6f693/Deblurring/MPRNet.py#L243-L245  

Our method ranked second. In fact, the winning solution also uses our supervised attention module (SAM). The challenge report will appear as a workshop paper in CVPR2021. We will notify you once it becomes publicly available.

**Comment by pingjun18-li** [comment]
Congratulations on your good grades again. And I will try to train on that data , looking forward to your project publicly available also.
