### ISSUE TITLE
CUDA out of memory in testing deblurring

### ISSUE THREAD

**Issue by Mr-doraemon** [swz30/MPRNet#35]
A CUDA Out of Memory error occurred when I was testing the DeBlurring model on the GTX 1080Ti in my datasets

`RuntimeError: CUDA out of memory. Tried to allocate 636.00 MiB (GPU 0; 10.92 GiB total capacity; 8.34 GiB already allocated; 21.38 MiB free; 10.34 GiB reserved in total by PyTorch)`

Can you help me solve this problem？

**Comment by ftaker887** [comment]
> A CUDA Out of Memory error occurred when I was testing the DeBlurring model on the GTX 1080Ti in my datasets
> 
> `RuntimeError: CUDA out of memory. Tried to allocate 636.00 MiB (GPU 0; 10.92 GiB total capacity; 8.34 GiB already allocated; 21.38 MiB free; 10.34 GiB reserved in total by PyTorch)`
> 
> Can you help me solve this problem？

Lower the size of your image. For example, if your image has a height of 1080px, resize the image to 512px or 256px.
