### ISSUE TITLE
Checkpoint about small model of MPRNet

### ISSUE THREAD

**Issue by kiyeonkimm** [swz30/MPRNet#38]
Hi! I try to use the small model of MPRNet.
Could you share a checkpoint for the small model of MPRNet mentioned [here](https://github.com/swz30/MPRNet/issues/6#issuecomment-787786769)?
Thanks

**Comment by swz30** [comment]
Hi @kiyeonkimm 

Here it is:  https://drive.google.com/drive/folders/1ksAIF_iO4W_Rmpvb92As6LA-i544b9OX?usp=sharing

**Comment by kiyeonkimm** [comment]
Thanks for your reply. 
Is the network trained for 3000 epochs mentioned in training.yml in the code provided?

**Comment by swz30** [comment]
Yes.
