### ISSUE TITLE
Can you provide the datasets link on Baidu Drive?

### ISSUE THREAD

**Issue by syzlhh** [swz30/MPRNet#42]
Hi, Thanks for your greate work and the open source code. Can you give the link of the datsets used in the paper on Baidu Drive?

**Comment by adityac8** [comment]
Hi @syzlhh 
We do not have access to Baidu Drive. Hence, we can't upload our datasets on it.

Thanks

**Comment by syzlhh** [comment]
> Hi @syzlhh
> We do not have access to Baidu Drive. Hence, we can't upload our datasets on it.
> 
> Thanks

OK! Thanks for your reply! We wil  try other methods to download the datasets.
