### ISSUE TITLE
AttributeError: 'CosineAnnealingLR' object has no attribute 'get_last_lr'

### ISSUE THREAD

**Issue by kzq666666** [swz30/MPRNet#44]
when I run deblurring task  ``python train.py`` , I get the error "AttributeError: 'CosineAnnealingLR' object has no attribute 'get_last_lr'" when the epoch is 3, how can i solve the problem

**Comment by adityac8** [comment]
Hi @kzq666666 

Could you tell your pytorch version.

Thanks

**Comment by kzq666666** [comment]
I install the package as the readme said. The version of pytorch is 1.1

**Comment by adityac8** [comment]
I just checked on my end and everything seems to work fine. Please make sure that you install warmup scheduler with 
`cd pytorch-gradual-warmup-lr; python setup.py install; cd ..`

**Comment by kzq666666** [comment]
Thanks
I will try it again.

**Comment by SugarWei** [comment]
我也遇到这个问题了，在线求解

**Comment by kzq666666** [comment]
你是不是也是用https://github.com/ildoonet/pytorch-gradual-warmup-lr这个包安装的&nbsp;warmup scheduler
当epoch到它设置的warmup_epoch=3时就报那个错误，我还找到解决方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月7日(星期五) 下午4:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [swz30/MPRNet] AttributeError: &#39;CosineAnnealingLR&#39; object has no attribute &#39;get_last_lr&#39; (#44)





 
我也遇到这个问题了，在线求解

**Comment by adityac8** [comment]
Hi

Please restrain from using any foreign language as it is easier for us to understand and your text might be helpful for others.

Thanks

**Comment by swz30** [comment]
The warmup scheduler is included in the repo https://github.com/swz30/MPRNet/tree/main/pytorch-gradual-warmup-lr

**Comment by kzq666666** [comment]
Thanks, I solve the problem,
I didn't install the warmup scheduler in the file folder before
Now i install it with
``cd pytorch-gradual-warmup-lr; python setup.py install; cd ..``
It works ! Thanks again for your answer！
