### ISSUE TITLE
some code problem

### ISSUE THREAD

**Issue by hellogry** [swz30/MPRNet#45]
![image](https://user-images.githubusercontent.com/12219867/117642179-96ae3f00-b1b9-11eb-9ab3-81def4a933a2.png)
The code reports the error as shown. How should I correct it?

**Comment by adityac8** [comment]
Please install pytorch version 1.1
Refer to https://github.com/swz30/MPRNet/issues/16#issuecomment-793698551

**Comment by hellogry** [comment]
![image](https://user-images.githubusercontent.com/12219867/117668113-31b61180-b1d8-11eb-891c-3e53e803d8ee.png)
Reinstalled pytorch 1.1 and still have this problem.

**Comment by adityac8** [comment]
Hi
Can you try installing numpy 1.18

Thanks

**Comment by jerryzz668** [comment]
still have this problem
