### ISSUE TITLE
'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by Niklas-gr-dot** [swz30/MPRNet#47]
Hello, I want to run the model. The shape of my torch is (3,4,224,224). But when I wanted to tun it, the following Error occurred. Can you please help me? Thank you! 

![image](https://user-images.githubusercontent.com/76098961/117810859-30c8c280-b260-11eb-9458-d9e381f5d992.png)

**Comment by adityac8** [comment]
Hi

Can you tell which file are you trying to run.

Thanks

**Comment by Niklas-gr-dot** [comment]
Hello! I'm trying to run the deblurring file.

**Comment by adityac8** [comment]
For **Deblurring**, we haven't used `torchsummary` in either `train` or `test` file. Are you getting an error after inserting any block of code.
