### ISSUE TITLE
Image Distortion While Using Pretrained Weight

### ISSUE THREAD

**Issue by AumXIV** [swz30/MPRNet#48]
I'm trying to deblur my image with the size around 100x100 pixels^2. And 2.97% of the outputs of the deblur have some distortion effect.
![228](https://user-images.githubusercontent.com/42962440/118067778-ce90ce80-b3d3-11eb-8aa7-5090a2bc0145.png) ![460](https://user-images.githubusercontent.com/42962440/118067787-d51f4600-b3d3-11eb-9dc3-25b33be8cba3.png) ![489](https://user-images.githubusercontent.com/42962440/118067817-e36d6200-b3d3-11eb-9337-8352dc5ae1d3.png) ![1970](https://user-images.githubusercontent.com/42962440/118067828-e9fbd980-b3d3-11eb-8487-5b2ab4921dde.png) ![2916](https://user-images.githubusercontent.com/42962440/118067847-f122e780-b3d3-11eb-8474-4bc109c046a1.png) ![2893](https://user-images.githubusercontent.com/42962440/118067849-f2ecab00-b3d3-11eb-9771-28bba8680b8b.png) ![3015](https://user-images.githubusercontent.com/42962440/118067921-0ef04c80-b3d4-11eb-940d-2d4486a626e8.png) ![1596](https://user-images.githubusercontent.com/42962440/118067948-1879b480-b3d4-11eb-8981-cd56f9d21afc.png) ![2978](https://user-images.githubusercontent.com/42962440/118067854-f41dd800-b3d3-11eb-8475-ab006fbc23eb.png) ![1588](https://user-images.githubusercontent.com/42962440/118068043-452dcc00-b3d4-11eb-9ce8-751bed9a9b2c.png)

Question;
1. What causes the problem?
2. Any method to fix it?

**Comment by adityac8** [comment]
Hi @AumXIV 

We did not observe such artifacts on any of the benchmark datasets. Maybe the input images have degradations other than blur.

Thanks

**Comment by AumXIV** [comment]
I found out that if we resize the image bigger (in my case 320 pixels) all the defects will disappear.
