### ISSUE TITLE
pytorch version issue

### ISSUE THREAD

**Issue by hhcs9527** [swz30/MPRNet#52]
Hi!
Thank you so much for your work!
I am wondering if anyone can run the model on PyTorch 1.8.1(stable version)?

Thanks

**Comment by adityac8** [comment]
Hi

I am able to **train** the models on pytorch 1.8.1.
However, the pretrained weights were provided for pytorch 1.1 and you might not be able to **test** using another version.

Thanks

**Comment by hhcs9527** [comment]
Hi

Thanks for the useful information!
I have another question for the evaluation of PSNR in image_utils.py in utils file. 

Why do you calculate the difference between prediction and target by 
imdff = torch.clamp(prd_img,0,1) - torch.clamp(tar_img,0,1)?

Thanks

**Comment by adityac8** [comment]
It is needed to compute the PSNR
![image](https://user-images.githubusercontent.com/19192257/118983947-08db0c80-b98e-11eb-869b-85bd9d66dd5e.png)

**Comment by hhcs9527** [comment]
Thanks for the formula for calculating PSNR.
I am wondering why do you perform torch.clamp(prd_img,0,1) before you perform imdff = torch.clamp(prd_img,0,1) - torch.clamp(tar_img,0,1).
In the formula that you provided, there is no such operation.

Could you tell me the reason for performing this torch.clamp(prd_img,0,1)?

Thanks

**Comment by hellogry** [comment]
hello, how can i test the real rain12 dataset?

**Comment by adityac8** [comment]
Hi @hhcs9527 

The outputs from the model might be a little outside the range of [0,1]. Hence, in order to make sure that the correct PSNR is calculated, we clamp the outputs between [0,1].

Thanks

**Comment by adityac8** [comment]
Hi @hellogry 

As per Table 1 in our paper, Rain12 is included in the **train set**. Hence we do not test on it.
![image](https://user-images.githubusercontent.com/19192257/119120818-c7099f00-ba3d-11eb-8b77-8d8174bf8029.png)

If you still want to test on Rain12 dataset, you can put the images at this path
https://github.com/swz30/MPRNet/blob/435f483b6433a6cf8d43f4df9c20eebba47587bb/Deraining/test.py#L25
and add **Rain12** at
https://github.com/swz30/MPRNet/blob/435f483b6433a6cf8d43f4df9c20eebba47587bb/Deraining/test.py#L44

Thanks

**Comment by hhcs9527** [comment]
Thanks!
The last question, I am wondering how do you measure the PSNR/SSIM(PSNR for 32.66 in your paper)? 
By running test.py, then run evaluate_GOPRO_HIDE.m?

Thanks

**Comment by adityac8** [comment]
Hi @hhcs9527 

Running `test.py` would generate the predictions. After that, running `evaluate_GOPRO_HIDE.m` would evaluate the PSNR/SSIM.

Thanks

**Comment by hhcs9527** [comment]
ok, I think I've done my questions, thanks!
