### ISSUE TITLE
Evaluate on RealBlur dataset.

### ISSUE THREAD

**Issue by huiwong96** [swz30/MPRNet#53]
Hi! Thank you for your wonderful work and great code!

I want to know is there a typo in the last of Deblurring readme.md file ?
## To reproduce PSNR/SSIM scores of the paper on RealBlur dataset, run
```
evaluate_RealBlur.m 
```
But there is only a `evaluate_RealBlur.py` file.
In other words, are the results in the paper on RealBlur dataset obtained by running this `.py` file? Or there is a `.m` file but it didn't upload.

**Comment by adityac8** [comment]
Hi @huiwong96 

Thank you for pointing out the typo. I have fixed it now. You need to run `evaluate_RealBlur.py` to get the paper PSNR/SSIM for RealBlur datasets.

Thanks

**Comment by huiwong96** [comment]
Thank you for your clarification !
