### ISSUE TITLE
About the real dataset

### ISSUE THREAD

**Issue by hellogry** [swz30/MPRNet#54]
![image](https://user-images.githubusercontent.com/12219867/119628806-03733b80-be40-11eb-935b-c7d739538768.png)
I would like to compare the performance of these two real rain images, can you send me the result image?

**Comment by swz30** [comment]
Hi @hellogry 

You can use the following file to perform inference on your own images: https://github.com/swz30/MPRNet/blob/main/demo.py

Here is an example for Deraining:
``` python demo.py --task Deraining --input_dir ./samples/input/ --result_dir ./samples/output/ ```
