### ISSUE TITLE
setting of pre-train model

### ISSUE THREAD

**Issue by hhcs9527** [swz30/MPRNet#55]
Hi 
Thanks for the great work!
I am wondering what is the setting of the pre-trained model that you provided for deblurring?
Is it n_feat=40, scale_unetfeats=40, scale_orsnetfeats=32 ? 
Or  n_feat=96, scale_unetfeats=48, scale_orsnetfeats=32 ?

Do you have them both? Are they suitable for PyTroch 1.8?

Thanks!

**Comment by adityac8** [comment]
Hi @hhcs9527 

The pre-tained model provided at 
https://drive.google.com/file/d/1QwQUVbk6YVOJViCsOKYNykCsdJSVGRtb/view?usp=sharing
uses the settings at
https://github.com/swz30/MPRNet/blob/1b8ec5c94506b7abfc0d71a62b58d32aa867bcfb/Deblurring/MPRNet.py#L239

We have only tested our models at PyTorch 1.1
If you are able to test it on other versions, please let us know.

Thanks

**Comment by hhcs9527** [comment]
Thanks for your information.
Could you provide the ssim  under the setting of  n_feat=40, scale_unetfeats=40, scale_orsnetfeats=32?
Thanks

**Comment by adityac8** [comment]
Hi @hhcs9527 
You can find the details about our light-weight Deblurring model at #38
Once you have the images, you can run [evaluate_GOPRO_HIDE.m](https://github.com/swz30/MPRNet/blob/main/Deblurring/evaluate_GOPRO_HIDE.m)

Thanks

**Comment by hhcs9527** [comment]
Thanks for your information, I tested both of them on RTX3090 and it works fine!
For the record,
Metod.       |  PSNR. | SSIM
origin         | 32.658 | 0.959
lite version| 31.87    | 0.952
Thanks again !!!

**Comment by adityac8** [comment]
Thank you for letting us know that our model is able to get the same performance with newer pytorch versions.

**Comment by dingyan1478** [comment]
> Hi @hhcs9527
> 
> The pre-tained model provided at https://drive.google.com/file/d/1QwQUVbk6YVOJViCsOKYNykCsdJSVGRtb/view?usp=sharing uses the settings at
> 
> https://github.com/swz30/MPRNet/blob/1b8ec5c94506b7abfc0d71a62b58d32aa867bcfb/Deblurring/MPRNet.py#L239
> 
> We have only tested our models at PyTorch 1.1 If you are able to test it on other versions, please let us know.
> 
> Thanks
HI @adityac8 
您好，按照您代码中默认的参数n_feat=96, scale_unetfeats=48, scale_orsnetfeats=32设置，您提供的预训练模型：https://drive.google.com/file/d/1QwQUVbk6YVOJViCsOKYNykCsdJSVGRtb/view?usp=sharing，模型的大小为80M左右，可是我 按照您代码中默认的参数n_feat=96, scale_unetfeats=48, scale_orsnetfeats=32训练的模型大小在240M左右，为什么会这样呢？是我的模型哪里除了问题吗？

**Comment by dingyan1478** [comment]
> Hi Thanks for the great work! I am wondering what is the setting of the pre-trained model that you provided for deblurring? Is it n_feat=40, scale_unetfeats=40, scale_orsnetfeats=32 ? Or n_feat=96, scale_unetfeats=48, scale_orsnetfeats=32 ?
> 
> Do you have them both? Are they suitable for PyTroch 1.8?
> 
> Thanks!

Sorry to bother you!

I would like to ask you whether you use the pre-trained model provided by the author for testing, or do you train yourself? According to the parameter settings mentioned by the author, the size of the model I trained is about 270M, but the size provided by the author is about 80M. Have you encountered this problem?

def __init__(self, in_c=3, out_c=3, n_feat=96, scale_unetfeats=48, scale_orsnetfeats=32, num_cab=8, kernel_size=3, reduction=4, bias=False):
