### ISSUE TITLE
Can it use tensorboard to look at the training log?

### ISSUE THREAD

**Issue by FrankLinxzx** [swz30/MPRNet#56]
Can it use tensorboard to look at the training loss or something ,it might be helpful for other people training

**Comment by Cjh2312** [comment]
run in Terminal       tensorboard --logdir=path

**Comment by FrankLinxzx** [comment]
> run in Terminal tensorboard --logdir=path

did it create log in MPRnet?

**Comment by adityac8** [comment]
Hi

We have not integrated tensorboard. However, we print the metrics at certain intervals at
https://github.com/swz30/MPRNet/blob/1b8ec5c94506b7abfc0d71a62b58d32aa867bcfb/Deblurring/train.py#L153
https://github.com/swz30/MPRNet/blob/1b8ec5c94506b7abfc0d71a62b58d32aa867bcfb/Deblurring/train.py#L163

Thanks
