### ISSUE TITLE
the number of iterations is inconsistent between code and paper ？

### ISSUE THREAD

**Issue by nachifur** [swz30/MPRNet#58]
Thank you for your work, MPRNet achieves the best performance in multiple tasks. 
But I am confused about the number of iterations. 
**paper:**
4.2. Implementation Details
The networks are trained on 256×256 patches with a batch size of 16 for **4×10^5 iterations**. 

**code:**
  MODE: 'Deblurring'
  NUM_EPOCHS: 3000

  MODE: 'Denoising'
  NUM_EPOCHS: 80

  MODE: 'Deraining'
  NUM_EPOCHS: 250

**Comment by adityac8** [comment]
Hi @nachifur 

The number of images for each of the methods are different, therefore the number of epochs are different. **4x10^5** is a close approximation of the number of iterations each model runs.

Thanks

**Comment by nachifur** [comment]
Thanks you.
