### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by zhaoguoqing12** [swz30/MPRNet#60]
请问如何在你发布的模型上继续训练？,我发现您发布的模型重量，与我训练的不一样

**Comment by swz30** [comment]
To resume the training, set  ```RESUME: True``` here: https://github.com/swz30/MPRNet/blob/1b8ec5c94506b7abfc0d71a62b58d32aa867bcfb/Deblurring/training.yml#L24

**Comment by dingyan1478** [comment]
> 请问如何在你发布的模型上继续训练？,我发现您发布的模型重量，与我训练的不一样

您好，请问您解决了这个问题了吗？我现在也面临了这个问题，下载的预训练模型大概是80M左右，可是自己训练的模型在240M左右，如果我加载预训练的模型，并继续进行训练的话，会出现loss很大的情况，甚至会爆炸，导致无法进行训练。
