### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by sherlybe** [swz30/MPRNet#62]
![image](https://user-images.githubusercontent.com/82870143/123727537-5ff4cb00-d8c4-11eb-9e63-29a05ba3adc2.png)

hi!  how to slove the error? thanks!

**Comment by zhangheng-h** [comment]
Maybe the “rgb_dir” is wrong.

**Comment by adityac8** [comment]
Hi @sherlybe 

As suggested by @zhangheng-h please make sure that the path `rgb_dir_test` exists.

Thanks

**Comment by sherlybe** [comment]
> Hi @sherlybe
> 
> As suggested by @zhangheng-h please make sure that the path `rgb_dir_test` exists.
> 
> Thanks
