### ISSUE TITLE
How much CUDA memory is required according to your default Settings?

### ISSUE THREAD

**Issue by zhangheng-h** [swz30/MPRNet#63]
when i'm running your codes,it's out of memory on our RTX3090 with 24G memory. we can only run it with batch 16 and patch 128 on tow GPU(15G used per GPU)
how should i balance the patch size and batch size.
thank you!

**Comment by bathcenter** [comment]
请问你复现成功了吗，我们可以交流一下吗

**Comment by hhcs9527** [comment]
I can run on RTX3090 with patch 256 and batch size 6.

**Comment by bathcenter** [comment]
我可以联系你一下吗，你是去噪、去模糊还是去雾，感谢你，等待你的回复

**Comment by hhcs9527** [comment]
沒問題 我是做去模糊

**Comment by bathcenter** [comment]
真的吗，我是从去噪转为去模糊的，我师兄做的就是去模糊，可以跟你学习吗

**Comment by hhcs9527** [comment]
hhcs9527@gmail.com . 我的email在這裡，我盡量回答

**Comment by bathcenter** [comment]
感谢你的联系方式，感谢

**Comment by zhangheng-h** [comment]
我的英文水平一看就是国人哈哈哈哈

**Comment by bathcenter** [comment]
你是中国？China！！

**Comment by zhangheng-h** [comment]
这么明显，肯定是中国人啊

**Comment by bathcenter** [comment]
me too 你的联系方式是什么，我可以联系你吗，感谢

**Comment by zhangheng-h** [comment]
qq3136560013，问题随便答就行，另外我是菜鸡。。。

**Comment by Iverson-zq** [comment]
> qq3136560013，问题随便答就行，另外我是菜鸡。。。

这里还有一个菜鸟 请问可以加入你们吗？
