### ISSUE TITLE
Bad case when testing on real world blur images with shot noise

### ISSUE THREAD

**Issue by asdf1996** [swz30/MPRNet#64]
Hi,
I have test the deblur model on real-world images.
Those images are produced with phones which are low quality and have too many shot noise.
Some results are still blur and some results lose many texture details and the edge is damaged.

I'd like to know which cause those bad cases.  Is this related to the network structure? 
The input image are divided into small region patches. Will those cause the inconsistency of the whole image and hence cause edge damage?
Besides, when the image are both blur and noisy, will the network tend to first to denoise? It may also cause texture loss.

Looking forward to your reply. Thanks！

**Comment by adityac8** [comment]
Hi @asdf1996 

We did not train our model on a joint denoising-deblurring task. This is why the model might not perform well on images with multiple degradations. If you haven't, could you try the [RealBlurJ model](https://github.com/swz30/MPRNet/issues/40#issuecomment-828429462) on your images.

Thanks
