### ISSUE TITLE
Running Evaluation on GOPRO

### ISSUE THREAD

**Issue by BLOO123** [swz30/MPRNet#65]
Hello! Thanks for the great work! I currently have an issue where i cannot run evaluate_GOPRO_HIDE.m .

OS: Windows 10 Pro

I am trying to write my own code in Python for the evaluation as I am unable to work with MATLAB. May i know which library is the following functions imported from?
```
[ssim_val = ssim(input, gt);
psnr_val = psnr(input, gt);]
```

On a side note, i noticed the updated GOPRO_Large has 2 blur datasets (gamma or no gamma). May i know which dataset is more aligned with the one used for training? Thanks!

**Comment by adityac8** [comment]
Hi @BLOO123 

You can have a look at 
https://github.com/swz30/MPRNet/blob/ee2c0eaf67031db9050b4194fdfc33e18065f65b/Deblurring/utils/image_utils.py#L5

You have to make sure the images are in `float32` and range `[0,1]`.

The function gives a similar performance in terms of `PSNR` on Python.
However, we could not find a similar solution for `SSIM` that gives similar results in MATLAB and Python.

For the GoPro dataset, we use the `Blur` folder(no gamma). You can find more details [here](https://github.com/swz30/MPRNet/issues/24#issuecomment-811716140).
Also, we have uploaded the zipped version of GoPro [here](https://drive.google.com/file/d/1Nl8NeHyT_zgNf7xFkshgwFTtsRlEcaRw/view?usp=sharing).

Thanks

**Comment by BLOO123** [comment]
Thank you! I will give it a try. Appreciate your help!
