### ISSUE TITLE
Mismatch of blurred input size and deblurred output size.

### ISSUE THREAD

**Issue by BLOO123** [swz30/MPRNet#67]
I encountered an issue when attempting to deblur on the Lai Synthetic Dataset.
This is a log of the input size (on the left) vs the output size(on the right) for 5 images:
```
natural_01.png
(701, 1024, 3) (702, 1023, 3)
natural_02.png
(684, 1024, 3) (683, 1023, 3)
natural_03.png
(605, 1024, 3) (605, 1023, 3)
natural_04.png 
(683, 1024, 3) (683, 1023, 3)
natural_05.png 
(768, 1024, 3) (768, 1023, 3)
```

As you can see, the output and input dimensions do not match. The input dimensions can be larger or smaller than the output dimensions. From the code, it seems that padding was performed to a factor of 8, which is subsequently cropped back (demo.py). 

As I am attempting to evaluate the PSNR and SSIM, the images are required to be of the same size. What would be the best approach? Would it be better to pad the image before cropping it to match the sizes? (Example below) I am more concerned about the accuracy of the evaluation which would change if the augmentation is inaccurate. Thanks!

```
def checksize2(orig,deblur):
    deb_h = deblur.shape[0]
    deb_w = deblur.shape[1]
    new_orig = cv2.copyMakeBorder( orig, 0, 8, 0, 8, cv2.BORDER_REFLECT)
    new_orig = new_orig[0:deb_h,0:deb_w]
    return new_orig
```

**Comment by adityac8** [comment]
Hi @BLOO123 

I just ran the `demo.py` on the shapes you described in the issue. I am able to get the same output shapes as that of the input. Could you please run it again and print the output shapes before image saving.

Thanks
