### ISSUE TITLE
evaluate the PSNR and SSIM of the data set GoPRO

### ISSUE THREAD

**Issue by bathcenter** [swz30/MPRNet#68]
Thanks for sharing. When I tried to evaluate the PSNR and SSIM of the data set GoPRO, I encountered some problems. For example, (1) after I input the test results and gt image path, I found that the operation was not successful on MATLAB, and (2) I found that the. M file lacked the code to define SSIM and PSNR. Is there something wrong with me
![bf196824dc68835128113985a9ebb67](https://user-images.githubusercontent.com/70826305/126954530-b419b696-e224-40ea-a35f-9e94903b6c29.png)
![a4bd91297b63a2006618932bf78c3bc](https://user-images.githubusercontent.com/70826305/126954539-cf739d02-1b67-4460-92f2-6989e7d4cfda.png)

**Comment by adityac8** [comment]
Hi,

We use the default MATLAB functions for PSNR and SSIM.
Could you make sure `img_num>0`.

Thanks

**Comment by Iverson-zq** [comment]
> Thanks for sharing. When I tried to evaluate the PSNR and SSIM of the data set GoPRO, I encountered some problems. For example, (1) after I input the test results and gt image path, I found that the operation was not successful on MATLAB, and (2) I found that the. M file lacked the code to define SSIM and PSNR. Is there something wrong with me
> ![bf196824dc68835128113985a9ebb67](https://user-images.githubusercontent.com/70826305/126954530-b419b696-e224-40ea-a35f-9e94903b6c29.png)
> ![a4bd91297b63a2006618932bf78c3bc](https://user-images.githubusercontent.com/70826305/126954539-cf739d02-1b67-4460-92f2-6989e7d4cfda.png)

你好，我想问一下，测试gopro数据集指标时，它那个m文件能不能不能在服务器上跑？
