### ISSUE TITLE
Some questions about NTIR2021 report?

### ISSUE THREAD

**Issue by pingjun18-li** [swz30/MPRNet#69]
Thank you for you great works.
In the NTIR2021 report, I observed that you have replaced losses functions with L1, Lms-ssim and Lvgg. Could you briefly introduce about that? Or what's the value of the argument of (α,β,γ) you set?

**Comment by swz30** [comment]
We use the following values α = 0.35 , β= 0.6, and γ= 0.05.

For more details on the loss function, check this paper "Learning Digital Camera Pipeline for Extreme Low-Light Imaging" https://arxiv.org/pdf/1904.05939.pdf
