### ISSUE TITLE
CUDA out of memory error at any batch size greater than 2

### ISSUE THREAD

**Issue by pranaysingh25** [swz30/MPRNet#71]
Hi,

I would like to appreciate your exemplary work.
I was very interested so i digged into the code after reading the paper.
While trying to run model training using the command given by you `python deblur.py --train` after putting the data and model at the right places.
I have been getting this error that 

> RuntimeError: CUDA out of memory. Tried to allocate xxx MiB (GPU 0; xxx GiB total capacity;  MiB already allocated; xxx GiB free; xxx MiB cached)

After some reading, i realised batch size could be the reason but it was already set at 16 default which is pretty standard but I any way reduced it to 8 then 4 then 3, it failed at them all. Only when I set it to 2 or 1, I could run the training. 
Also I was using an extremely short version of GOPRO data where I had put only 800 images in training folder and also I had set it just 2 epochs as I just wanted to run the training functionality. I went on to reduce the training data further to just 64! Also testing data to 64! Still it failed to load at same number, which is any batch size greater than 2, it failed.
Also, I have GPU 24 GB memory and 32 GB ram, I have enough disk space, to be particular I am running it on google colab.

I would also like to say that I have already used the `python deblur.py --apply` for my sample test images on pretrained model and I had absolutely no problem using it on 16 batch size.
Just wanted to know what's missing, if you could help that would be really helpful in my further experiments.

Thanks,
Pranay

**Comment by candygogogogo** [comment]
> So self.conv1 is the point where memory shoots up.
> I had few doubts in mind whether the model is taking complete data in memory and then assigning batches or its creating buffer of subsequent batches while processing the current batch, because given the size of the data i have catered to it its hard to understand the memory issue.

I think this is a questionable public code

**Comment by adityac8** [comment]
Hi

We use 4 Tesla V100s with 32GB memory each to train the Deblurring model with batch size 16.
You can find an appropriate batch size based on the number of GPUs and the memory capacity of each GPU.

Thanks
