### ISSUE TITLE
Rain13k contains 13,711 images, missing 1?

### ISSUE THREAD

**Issue by vztu** [swz30/MPRNet#74]
Hi I downloaded your Rain13K dataset [here](https://drive.google.com/corp/drive/folders/1Hnnlc5kI0v9_BtfMytC2LR5VpLAFZtVe) and found it contains 13,711 image pairs. However, your paper states there are 13,712 image pairs. Wondering is there a single pair missing?

**Comment by adityac8** [comment]
The size for 1 image was not correct and hence we remove it. There are 13711 image pairs for download.
