### ISSUE TITLE
model size

### ISSUE THREAD

**Issue by chenloveheimei** [swz30/MPRNet#79]
hello,my name is Long.
 I downloaded your pretrain model and the model's size is about 80M.
When I train a new model,I  found the model's size is 241M.what should I do can reduce the size?
thank you.

**Comment by adityac8** [comment]
The discrepancy might occur if you use the arguments of the Deblurring task for Deraining as the Deblurring model is heavier.

**Comment by dingyan1478** [comment]
> hello,my name is Long. I downloaded your pretrain model and the model's size is about 80M. When I train a new model,I found the model's size is 241M.what should I do can reduce the size? thank you.

您好，我也遇到了这个问题， 我下载的作者提供的去模糊的预训练模型大概是80M左右，可是如果如果我自己训练去雾的模型，得到的模型大概240M左右，图一是预训练的模型，图二是我自己训练的模型。
![image](https://user-images.githubusercontent.com/74007964/145130555-f43ae57c-77b5-46b4-a2ab-7464329452cc.png)
![image](https://user-images.githubusercontent.com/74007964/145130635-5fa71031-f513-4283-8bbc-d902fbe8fb96.png)
如果您解决了这个问题，非常感谢您能够帮助我一下，这个问题困扰了我好久。
再次感谢！

**Comment by hust-lidelong** [comment]
已收到邮件，谢谢

**Comment by dingyan1478** [comment]
> 已收到邮件，谢谢

您好！麻烦请问一下，这个问题您解决了吗？

**Comment by dingyan1478** [comment]
> 已收到邮件，谢谢

很抱歉再次打扰到您，想问一下您的这个问题解决了吗？当我自己训练网络模型的时候会得到大概240M左右的模型，但是加载作者使用的预训练模型的话74M左右，而且，如果在作者预训练的权重上继续进行训练的话，模型的大小还是240左右，是哪里出了问题吗？
非常期待您的回复！

**Comment by ak-karimzai** [comment]
@dingyan1478 can you share plz loss dependency and psnr and ssim value in each epoch?
