### ISSUE TITLE
 Some questions about Time

### ISSUE THREAD

**Issue by dingyan1478** [swz30/MPRNet#81]
Hi！
I want to know what the time mentioned in Table 7 refers to? Is it time to test a  picture？

![屏幕截图 2021-10-04 085814](https://user-images.githubusercontent.com/74007964/135780026-ccc82628-aba0-40e2-9d54-e48ca762bd92.png)

**Comment by adityac8** [comment]
Yes, it refers to the time taken by various architectures to pass a test image of the GoPro dataset.

**Comment by dingyan1478** [comment]
Thanks!



At 2021-10-04 16:12:11, "Aditya Arora" ***@***.***> wrote:

Yes, it refers to the time taken by various architectures to pass a test image of the GoPro dataset.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
