### ISSUE TITLE
真实下雨数据集效果不佳

### ISSUE THREAD

**Issue by zhangliukun** [swz30/MPRNet#85]
论文中的模拟下雨数据效果不错，但是这个模拟的雨天太简单了，真实场景中的雨天完全不是这个效果。所以使用网络用在真实数据上效果几乎没有？

**Comment by lonely6628** [comment]
> 论文中的模拟下雨数据效果不错，但是这个模拟的雨天太简单了，真实场景中的雨天完全不是这个效果。所以使用网络用在真实数据上效果几乎没有？

你好，我也是做去雨方向的，方便加一下你的微信吗，我的微信号是lonely_6628

**Comment by adityac8** [comment]
Hi @zhangliukun 

The models trained on synthetic datasets might not perform that well on real degradations.
This is further discussed here. https://github.com/kuijiang0802/MSPFN/issues/13


Thanks
