### ISSUE TITLE
Output is the same as input image

### ISSUE THREAD

**Issue by toshaklg** [swz30/MPRNet#90]
Hello!
First off I want to say thanks for sharing such a nice model! I am far from proficiency in ML stuff, so to me it looks like it does magic with the images, but there is an issue. 

Basically, I want to see how well a pre-trained denosing model copes with noise on Sentinel-1 SAR images. The original data format is rather tricky, so I created a subsets that consists of png images in RGB format that look like this:
![e1](https://user-images.githubusercontent.com/43007372/140039243-13adf39f-6aad-48bd-92c1-acbbf3b2fc11.png)

Feeding this kind of images to the model allows me to get a very nice output, like that:
![e1d](https://user-images.githubusercontent.com/43007372/140039376-177a39f6-3364-452d-8ce1-75a289d5d947.png)

However, some output is exactly the same as input, for example here:
![e10](https://user-images.githubusercontent.com/43007372/140039817-b2cdef3f-9b15-47d2-92af-080c13d8e5e1.png)
Feels like the model just didn't do anything with that, but at the same time no errors in the output terminal.

All images are converted to RGB png format from RGBA, all other parameters look the same.

Maybe you have any thoughts why it happens? 

P.S. What I am thinking about, is that there were no such images in the training dataset and the model doesn't know what to do with that, but I am just speculating here. 

Many thanks

**Comment by adityac8** [comment]
Hi @toshaklg 

For images of different sensors, such as SAR, you would need to train a separate model with clean/degraded image pairs of that format.

Thanks
