### ISSUE TITLE
Loss problem

### ISSUE THREAD

**Issue by jiaaihhy** [swz30/MPRNet#91]
when I train deblur, 
        loss_char = np.sum([criterion_char(restored[j],target) for j in range(len(restored))])
then report
       can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
    
  use np.sum, grad may be none, how to do it?
thank you

**Comment by ONEISALL-h** [comment]
Hello, I have the same problem. Have you solved it ?
Thank you

**Comment by adityac8** [comment]
Hi @jiaaihhy 

You can use the following snippet
```
loss_char = sum([criterion_char(restored[j],target) for j in range(len(restored))])
```

Thanks
