### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by bathcenter** [swz30/MPRNet#92]
Hello, I'm sorry to bother you. I had a problem training the rain dataset. My friend has never encountered such a situation, so I want you to help me see the reason for this mistake,

Because of the equipment, I removed your first stage. The input size is 128, and the BS is 8. Such a problem occurs (as shown in the figure). In the first 200 epoch, PSNR is rising, and it suddenly becomes 5.2673 at 250, and it is still at 4.7944 at 500. What is the reason
![3fd54b69acc9af8b64353e20c54a1bc](https://user-images.githubusercontent.com/70826305/141878993-35a8c0bd-914e-436c-a629-3a364359d01e.jpg)
![fe6d0bc30374a7682fc92e6d5519800](https://user-images.githubusercontent.com/70826305/141878997-888d0b10-766f-4f3e-b3c2-fbfbc8b56214.jpg)
![b0e572c00afb64ad28e0af177f5f7a3](https://user-images.githubusercontent.com/70826305/141879005-5ff6beef-7c35-459a-8ee7-eef78765c520.jpg)

**Comment by adityac8** [comment]
Hi @bathcenter 
 You can have a look here. https://github.com/swz30/MPRNet/issues/51#issuecomment-843802843
