### ISSUE TITLE
Training Problems

### ISSUE THREAD

**Issue by dingyan1478** [swz30/MPRNet#93]
Hi! 
I'm sorry to bother you.I want to use my own dataset to fine tune your trained model, but no matter how I change the corresponding parameters, the value of the loss function is always large, and there will be gradient explosion. Do you know why?
![image](https://user-images.githubusercontent.com/74007964/142755518-aa9e1202-6ea0-4267-8c3e-338fc58002fa.png)

**Comment by adityac8** [comment]
You can have a look here. https://github.com/swz30/MPRNet/issues/51#issuecomment-843802843
