### ISSUE TITLE
训练模型大小

### ISSUE THREAD

**Issue by dingyan1478** [swz30/MPRNet#95]
很抱歉再次打扰到你，我有一个问题，就是我加载您训练好的模型，这个模型的大小显示为76.79M左右，如图一，但是如果我自己训练网络，没有更改任何的网络结构，训练出的模型的大小为232M左右，如图二，你能知道是什么原因吗？
![image](https://user-images.githubusercontent.com/74007964/143736031-56007d10-53a6-4f3e-9821-c9b9f28032cf.png)
![image](https://user-images.githubusercontent.com/74007964/143736037-fd99312d-9e18-4085-97e8-701850bc405a.png)
还有，如果我加载您预训练的模型，并在这个模型上进行微调，这个时候训练的模型还是232M左右，而且微调的时候无论我怎样调整学习率和训练策略，都会出现梯度爆炸的情况？这个问题困扰了我很久，很希望能够得到您的回答！
非常感谢！

**Comment by dingyan1478** [comment]
> 很抱歉再次打扰到你，我有一个问题，就是我加载您训练好的模型，这个模型的大小显示为76.79M左右，如图一，但是如果我自己训练网络，没有更改任何的网络结构，训练出的模型的大小为232M左右，如图二，你能知道是什么原因吗？ ![image](https://user-images.githubusercontent.com/74007964/143736031-56007d10-53a6-4f3e-9821-c9b9f28032cf.png) ![image](https://user-images.githubusercontent.com/74007964/143736037-fd99312d-9e18-4085-97e8-701850bc405a.png) 还有，如果我加载您预训练的模型，并在这个模型上进行微调，这个时候训练的模型还是232M左右，而且微调的时候无论我怎样调整学习率和训练策略，都会出现梯度爆炸的情况？这个问题困扰了我很久，很希望能够得到您的回答！ 非常感谢！

**Comment by dante1024** [comment]
> 很抱歉再次打扰到你，我有一个问题，就是我加载您训练好的模型，这个模型的大小显示为76.79M左右，如图一，但是如果我自己训练网络，没有更改任何的网络结构，训练出的模型的大小为232M左右，如图二，你能知道是什么原因吗？ ![image](https://user-images.githubusercontent.com/74007964/143736031-56007d10-53a6-4f3e-9821-c9b9f28032cf.png) ![image](https://user-images.githubusercontent.com/74007964/143736037-fd99312d-9e18-4085-97e8-701850bc405a.png) 还有，如果我加载您预训练的模型，并在这个模型上进行微调，这个时候训练的模型还是232M左右，而且微调的时候无论我怎样调整学习率和训练策略，都会出现梯度爆炸的情况？这个问题困扰了我很久，很希望能够得到您的回答！ 非常感谢！

我也有这个问题，下载的预训练模型比我自己训的模型大，请问你知道是什么原因吗？
