### ISSUE TITLE
SIDD evaluation data sets used to evaluate the denoising model in the paper.

### ISSUE THREAD

**Issue by pic-kk** [swz30/MPRNet#97]
I want to know the SIDD evaluation data sets used to evaluate the denoising model in the paper.
Is this Noisy sRGB data (Mirror1) and Ground-truth sRGB data (Mirror1) at the SIDD Validation Data and Ground Truth section in the following link (https://www.eecs.yorku.ca/~kamel/sidd/benchmark.php)?

**Comment by adityac8** [comment]
Hi @pic-kk 

You need to use **SIDD Validation Data and Ground Truth** for replicating Table 5 in our paper.

Thanks
